# NumPy Laboratory Practice Questions

## Array Creation & Properties

### 1. Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.

In [4]:
# creating an numpy array
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print(array)
print("Shape:", array.shape)
print("size of the array : ",array.size)
print("data type of the array : ",array.dtype)

[10 20 30 40 50]
Shape: (5,)
size of the array :  5
data type of the array :  int64


2. Create a 3 × 4 array containing numbers from 1 to 12.

In [5]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 3. Create an array of zeros, an array of ones, and an identity matrix.

In [10]:
# matrix of zeros
import numpy as np
zeros = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(zeros)
print()

# matrix of one's
ones = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(ones)
print()

#matrix of identity
iden = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(iden)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 4. Generate all even numbers between 10 and 50 using np.arange().

In [11]:
import numpy as np
even = np.arange(10, 51, 2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### 5. Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().

In [12]:
import numpy as np
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Array Arithmetic

### 6. Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.

In [13]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


### 7. Calculate the square and cube of every element in a NumPy array.

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Square:", arr ** 2)
print("Cube:", arr ** 3)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


### 8. Increase every element of an array by 15%.

In [15]:
import numpy as np
arr = np.array([100, 200, 300, 400])
new_arr = arr * 1.15

print("Original array:", arr)
print("After 15% increase:", new_arr)

Original array: [100 200 300 400]
After 15% increase: [115. 230. 345. 460.]


### 9. Given two arrays, find their element-wise maximum and minimum.

In [16]:
import numpy as np
a = np.array([10, 50, 30, 80, 20])
b = np.array([20, 40, 35, 60, 25])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [20 50 35 80 25]
Minimum: [10 40 30 60 20]


## Indexing & Slicing

### 10. Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.

In [17]:
import numpy as np
arr = np.arange(21)
print("Array:", arr)
print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


### 11. Replace the first five elements of an array with 100.

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


### 12. Create an array and demonstrate the difference between a slice/view and a copy.

In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# View
view = arr[1:4]
view[0] = 100
print("Original after changing view:", arr)

# Copy
arr2 = np.array([10, 20, 30, 40, 50])
copy = arr2[1:4].copy()
copy[0] = 200
print("Original after changing copy:", arr2)
print("Copy:", copy)

Original after changing view: [ 10 100  30  40  50]
Original after changing copy: [10 20 30 40 50]
Copy: [200  30  40]


### 13. Reverse a NumPy array using slicing.

In [20]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
reverse = arr[::-1]

print("Original:", arr)
print("Reversed:", reverse)

Original: [10 20 30 40 50]
Reversed: [50 40 30 20 10]


## 2-D Array Indexing & Slicing

### 14. Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.

In [21]:
import numpy as np
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


### 15. From the matrix above, extract the sub-matrix [[20,30],[50,60]].

In [22]:
import numpy as np
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

sub_matrix = matrix[0:2, 1:3]
print(sub_matrix)

[[20 30]
 [50 60]]


### 16. Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.

In [24]:
import numpy as np
matrix = np.arange(1, 26).reshape(5, 5)
print("Matrix:")
print(matrix)
print()
print("First row:", matrix[0])
print("Last column:", matrix[:, -1])
print("Middle element:", matrix[2, 2])
print()
print("Top-left 3x3 matrix:")
print(matrix[:3, :3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13

Top-left 3x3 matrix:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


## Reshaping & Transpose

### 17. Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

In [25]:
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 18. Reshape a 1-D array into a 2 × 5 matrix.

In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 19. Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

In [27]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original matrix:")
print(matrix)
print()
print("Transpose:")
print(matrix.T)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 20. Use transpose() and swapaxes() on a 3-D array.

In [29]:
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)
print("Original array:")
print(arr)

print("\nUsing transpose():")
print(arr.transpose(1, 0, 2))

print("\nUsing swapaxes():")
print(arr.swapaxes(0, 1))

Original array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Using transpose():
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

Using swapaxes():
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


### Matrix Operations

### 21. Create two 3 × 3 matrices and perform element-wise addition and multiplication.

In [32]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("square :")
print(arr**2)

square :
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 22. Calculate the matrix product of two compatible matrices using np.dot().

In [37]:
import numpy as np
arr1 = ([[1,2],[3,4]])
arr2 = ([[6,7],[8,9]])
result = np.dot(arr1,arr2)
print(arr1)
print()
print(arr2)
print()
print(result)

[[1, 2], [3, 4]]

[[6, 7], [8, 9]]

[[22 25]
 [50 57]]
