#NumPy

## NumPy is a python library, was created in 2005 by Travis Oliphant
## Numpy is used for working with arrays. NumPy is short for "Numerical Python". 50x faster than Traditional Python lists

In [2]:
#importing numspy library
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


## different ways to create numpy array

In [4]:
# to create an ndarray, we caan pass a list,tuple or
# other array like object
# create 2d array
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [5]:
#to see the dimension
print(arr3.ndim)

2


In [10]:
# create 3d array
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9],[2,4,6]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [2 4 6]]]
3


In [9]:
#Numpy Array indexing
arr5 = np.array([1,2,3,4,5])
print(arr5[2])

3


In [14]:
print(arr5[0:3])

# using negative index
print(arr5[-1])
print(arr5[-2:-1])

[1 2 3]
5
[4]


## Ques : get third and fourth elements sum from the following array

In [15]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


## Ques : Acess the element on the first row , second column

In [18]:
import numpy as np
arr6 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6)
print("Second element of first row is : ",arr6[0][1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Second element of first row is :  2


## Ques : access the element on the 2nd row and 5th column

In [19]:
import numpy as np
arr7 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr7)
print("5th element on the 2nd row :",arr7[1][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on the 2nd row : 10


## Ques : print the element at 1st row last element

In [20]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,8]]])
print(arr)
print(arr[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 5 8]]]
6


In [22]:
# print 2nd last element from the 2nd row
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("Last element from 2nd dim: ",arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [23]:
# slicing the array from 1 to 5 index from the following
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])

print(arr)
print(arr[1:5])


[1 2 3 4 5 6 7 8]
[2 3 4 5]


In [24]:
# slice element from index 4 to the end of the array
print(arr[4:])

#slice element from beginning to index 4(not included)
print(arr[:4])

[5 6 7 8]
[1 2 3 4]


In [25]:
# Negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


In [27]:
# use the step value to determine the step of the following
print(arr[1:5:2])

#return every other element from the entire element
print(arr[::2])

[2 4]
[1 3 5 7]


## slicing 2D array

In [28]:
# 2d array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [30]:
# from both rows of element
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print()
print(arr[0:2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[2 3 4]
 [7 8 9]]


# Data Types in NumPy

## Numpy has some extra data types , and refer to data types whith one character , like i for integer , u for unsigned integers ,etc

##i- integer
##b- boolean
##u- unsigned integer
##f - float
##c - complex float

In [32]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [35]:
# creating array with defined data type
import numpy as np
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [36]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [37]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='I')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
uint32


In [40]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='b')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int8


In [41]:
# change data type from float to integer by using i
import numpy as np
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Numpy Array Copy vs View

## the main differnce btw a copy and a view of an array is that the copy is a new array , and the view is just a view of the original array

In [44]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 32
print("original array : ",arr)
print()
print("copy array : ",x)

original array :  [32  2  3  4  5]

copy array :  [1 2 3 4 5]


## View

In [45]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 32
print("original array : ",arr)
print()
print("copy array : ",x)

original array :  [32  2  3  4  5]

copy array :  [32  2  3  4  5]


## Numpy Array Shape

In [47]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr.shape)

(2, 5)


## Numpy Array Reshaping

In [51]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Flattening the array
## reshape(-1)

In [52]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


## NumPy array iterating
## Iterating means going through elements one by one
## as we deal with multi - dimensional array in numpy , we can do this using basic for loop of python